# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Test.py
# Created on: 2019-10-24 16:28:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
surveyPoint = "surveyPoint"
surveyPoint_Buffer = "C:\\Users\\srv_veralab\\Documents\\ArcGIS\\Default.gdb\\surveyPoint_Buffer"

# Process: Buffer
arcpy.Buffer_analysis(surveyPoint, surveyPoint_Buffer, "", "FULL", "ROUND", "NONE", "")

