# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2019-10-24 16:27:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
surveyPoint = "surveyPoint"
surveyPoint_Buffer2 = ""

# Process: Buffer
arcpy.Buffer_analysis("", surveyPoint_Buffer2, "", "FULL", "ROUND", "NONE", "")

